### ISSUE TITLE
New Update

### ISSUE THREAD

**Issue by Sheime** [debbietools/OldBot#1]
Hello,
Download the newest version but can't run it .
![error](https://user-images.githubusercontent.com/26493748/41593130-5134b69c-73bf-11e8-9460-5b1f9a5eca0f.jpg)
Do you plan soon update or have any resolve for it ?

**Comment by debbietools** [comment]
Hello!

Thanks for contacting me, it's fixed, can you give a look?


Thanks!
Best regards.


________________________________
De: Sheime <notifications@github.com>
Enviado: terça-feira, 19 de junho de 2018 07:50
Para: debbietools/OldBot
Cc: Subscribed
Assunto: [debbietools/OldBot] New Update (#1)


Hello,
Download the newest version but can't run it .
[error]<https://user-images.githubusercontent.com/26493748/41593130-5134b69c-73bf-11e8-9460-5b1f9a5eca0f.jpg>

[https://user-images.githubusercontent.com/26493748/41593130-5134b69c-73bf-11e8-9460-5b1f9a5eca0f.jpg]

Do you plan soon update or have any resolve for it ?
