### ISSUE TITLE
Auto Haste/UtamoVita not working on OTClient

### ISSUE THREAD

**Issue by Felipe1993** [debbietools/OldBot#10]
Somos you he bien to to add options yo make it works on otclient?

**Comment by tolmai** [comment]
Maybe auto haste could not check the small icon of hungry.. maybe the best solution for auto haste/utamo vita is calculate how much second this magic spell stay active, and renew the spell in +1 second after the spell ends.

**Comment by debbietools** [comment]
If you want to use Auto Haste/Utamo Vita based on the time of the spell you can use the Timer Tools on the Main tab of the bot.

**Comment by debbietools** [comment]
Closed due to no answer.
